import {
  useDateParam,
  useIntParam,
  useStringArrayParam,
  useStringParam,
} from "betterouter/page-router";
import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

const Home: NextPage = () => {
  const [foo, setFoo] = useStringParam("foo", "foo");
  const [bar, setBar] = useIntParam("bar", 1);
  const [date, setDate] = useDateParam("date");
  const [arr, setArr] = useStringArrayParam("arr");

  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          {foo}, {bar}, {date?.toISOString()},{arr}
        </div>
        <button
          onClick={() => {
            router.push({ pathname: router.pathname });
          }}
        >
          clear
        </button>
        <button
          onClick={() => {
            setFoo("a");
            setBar(2);
          }}
        >
          foo:a, bar:2
        </button>
        <button
          onClick={() => {
            setFoo("b");
            setBar(3);
          }}
        >
          foo:b, bar:3
        </button>
        <button
          onClick={() => {
            setFoo(undefined);
            setBar(undefined);
          }}
        >
          clear foo/bar
        </button>
        <button
          onClick={() => {
            router.push({
              pathname: router.pathname,
              query: { foo: "aaaa", bar: "6" },
            });
          }}
        >
          router foo:aaaa, bar:6
        </button>
        {date?.toISOString()}
        <button
          onClick={() => {
            setDate(new Date());
          }}
        >
          date
        </button>
        <button onClick={() => setArr([])}>arr</button>
      </div>
    </>
  );
};

export default Home;
